"use client";
import { Provider } from "react-redux";
import  store  from "../store/store";
import '@/app/asset/css/material-design-iconic-font.min.css'
import '@/app/asset/css/material-design-iconic-font.min.css'
import '@/app/asset/css/font-awesome.min.css'
import '@/app/asset/css/fontawesome-stars.css'
import '@/app/asset/css/meanmenu.css'
import '@/app/asset/css/owl.carousel.min.css'
import '@/app/asset/css/slick.css'
import '@/app/asset/css/animate.css'
import '@/app/asset/css/jquery-ui.min.css'
import '@/app/asset/css/venobox.css'
import '@/app/asset/css/nice-select.css'
import '@/app/asset/css/magnific-popup.css'
import '@/app/asset/css/bootstrap.min.css'
import '@/app/asset/css/helper.css'
import '@/app/asset/style.css'
import '@/app/asset/css/responsive.css'
import '@/app/asset/custom-style.css'
import '@/app/components/slider/lib/components/styles/index.css'
import '@/app/asset/css/sliderstyle.css'
import { useEffect } from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  


  console.log('store:',store);
  return (
     <html lang="en">
       <Provider store={store}>
          <body>{children}</body>
      </Provider>
    </html>
  )
}


